package UI;

import controlador.Controlador;
import javax.swing.JOptionPane;
import modelo.Funcionario;

/**
 *
 * @author Igorjr19
 */

public class TelaInicial extends javax.swing.JFrame {

    private Controlador control = new Controlador();

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titulo = new javax.swing.JLabel();
        btnResumoDepartamentos = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();
        panelRelatorioFaixa = new javax.swing.JPanel();
        labelDepartamtoFaixa = new javax.swing.JLabel();
        labelDe = new javax.swing.JLabel();
        spinnerMin = new javax.swing.JSpinner();
        labelA = new javax.swing.JLabel();
        spinnerMax = new javax.swing.JSpinner();
        btnResumoDepFaixa = new javax.swing.JToggleButton();
        panelCadastro = new javax.swing.JPanel();
        labelCadastro = new javax.swing.JLabel();
        buttonCadastro = new javax.swing.JButton();
        comboNivel = new javax.swing.JComboBox<>();
        labelComboNivel = new javax.swing.JLabel();
        panelBuscar = new javax.swing.JPanel();
        comboCodNome = new javax.swing.JComboBox<>();
        labelComboCodNome = new javax.swing.JLabel();
        textCodNome = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JToggleButton();
        panelRelatorioFaixa1 = new javax.swing.JPanel();
        labelFuncionariaFaixa = new javax.swing.JLabel();
        labelDe1 = new javax.swing.JLabel();
        spinnerMinFunc = new javax.swing.JSpinner();
        labelA1 = new javax.swing.JLabel();
        spinnerMaxFunc = new javax.swing.JSpinner();
        btnResumoFuncFaixa = new javax.swing.JToggleButton();
        panelExibirFuncionarios = new javax.swing.JPanel();
        buttonTodosFuncionarios = new javax.swing.JButton();
        buttonFuncionariosTecnicos = new javax.swing.JButton();
        buttonFuncionariosDocentes = new javax.swing.JButton();
        buttonFuncionariosSubstitutos = new javax.swing.JButton();
        buttonFuncionariosEfetivos = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labelComboDepartamento = new javax.swing.JLabel();
        btnInfoDepartamento = new javax.swing.JButton();
        comboDepartamento = new javax.swing.JComboBox<>();
        buttonRelatorioGeral = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Universidade");

        titulo.setFont(new java.awt.Font("Segoe UI", 0, 32)); // NOI18N
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText("Faculdade de Presidente Prudente");

        btnResumoDepartamentos.setText("Resumo dos Departamentos");
        btnResumoDepartamentos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResumoDepartamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumoDepartamentosActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("Relatórios");

        panelRelatorioFaixa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelDepartamtoFaixa.setText("<html>Relatório de Departamentos com gasto em faixa");

        labelDe.setText("De:");

        spinnerMin.setValue(1000);

        labelA.setText("A:");

        spinnerMax.setValue(1000);

        btnResumoDepFaixa.setText("<html>Relatório Departamento Faixa");
        btnResumoDepFaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResumoDepFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumoDepFaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRelatorioFaixaLayout = new javax.swing.GroupLayout(panelRelatorioFaixa);
        panelRelatorioFaixa.setLayout(panelRelatorioFaixaLayout);
        panelRelatorioFaixaLayout.setHorizontalGroup(
            panelRelatorioFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatorioFaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatorioFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelatorioFaixaLayout.createSequentialGroup()
                        .addComponent(labelDepartamtoFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelatorioFaixaLayout.createSequentialGroup()
                        .addGroup(panelRelatorioFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnResumoDepFaixa, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelRelatorioFaixaLayout.createSequentialGroup()
                                .addComponent(labelDe)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelA)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        panelRelatorioFaixaLayout.setVerticalGroup(
            panelRelatorioFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelatorioFaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDepartamtoFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRelatorioFaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA)
                    .addComponent(labelDe)
                    .addComponent(spinnerMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResumoDepFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelCadastro.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelCadastro.setText("Cadastrar Funcionário:");

        buttonCadastro.setText("Cadastrar Funcionário");
        buttonCadastro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCadastroActionPerformed(evt);
            }
        });

        comboNivel.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Técnico", "Efetivo", "Substituto" }));
        comboNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboNivelActionPerformed(evt);
            }
        });

        labelComboNivel.setText("Selecione o Nível do Funcionário");

        javax.swing.GroupLayout panelCadastroLayout = new javax.swing.GroupLayout(panelCadastro);
        panelCadastro.setLayout(panelCadastroLayout);
        panelCadastroLayout.setHorizontalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelComboNivel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCadastro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelCadastroLayout.setVerticalGroup(
            panelCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelComboNivel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCadastro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        comboCodNome.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Código" }));
        comboCodNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboCodNomeActionPerformed(evt);
            }
        });

        labelComboCodNome.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        labelComboCodNome.setLabelFor(comboCodNome);
        labelComboCodNome.setText("Buscar Funcionário pelo");

        textCodNome.setText("Nome ou Código");
        textCodNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textCodNomeMouseClicked(evt);
            }
        });
        textCodNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCodNomeActionPerformed(evt);
            }
        });

        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBuscarLayout = new javax.swing.GroupLayout(panelBuscar);
        panelBuscar.setLayout(panelBuscarLayout);
        panelBuscarLayout.setHorizontalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBuscarLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboCodNome, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelComboCodNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textCodNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        panelBuscarLayout.setVerticalGroup(
            panelBuscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBuscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelComboCodNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboCodNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textCodNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelRelatorioFaixa1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelFuncionariaFaixa.setText("<html> Funcionários com salário em faixa");

        labelDe1.setText("De:");

        spinnerMinFunc.setValue(1000
        );

        labelA1.setText("A:");

        spinnerMaxFunc.setValue(1000
        );

        btnResumoFuncFaixa.setText("<html>Relatório Funcionários Faixa");
        btnResumoFuncFaixa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResumoFuncFaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResumoFuncFaixaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRelatorioFaixa1Layout = new javax.swing.GroupLayout(panelRelatorioFaixa1);
        panelRelatorioFaixa1.setLayout(panelRelatorioFaixa1Layout);
        panelRelatorioFaixa1Layout.setHorizontalGroup(
            panelRelatorioFaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRelatorioFaixa1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRelatorioFaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRelatorioFaixa1Layout.createSequentialGroup()
                        .addComponent(labelFuncionariaFaixa)
                        .addContainerGap())
                    .addGroup(panelRelatorioFaixa1Layout.createSequentialGroup()
                        .addGroup(panelRelatorioFaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnResumoFuncFaixa)
                            .addGroup(panelRelatorioFaixa1Layout.createSequentialGroup()
                                .addComponent(labelDe1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerMinFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelA1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerMaxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12))))
        );
        panelRelatorioFaixa1Layout.setVerticalGroup(
            panelRelatorioFaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRelatorioFaixa1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelFuncionariaFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRelatorioFaixa1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelA1)
                    .addComponent(labelDe1)
                    .addComponent(spinnerMinFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerMaxFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResumoFuncFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelExibirFuncionarios.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonTodosFuncionarios.setText("Exibir Todos Funcionários");
        buttonTodosFuncionarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonTodosFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTodosFuncionariosActionPerformed(evt);
            }
        });

        buttonFuncionariosTecnicos.setText("Exibir Funcionários Técnicos");
        buttonFuncionariosTecnicos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFuncionariosTecnicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionariosTecnicosActionPerformed(evt);
            }
        });

        buttonFuncionariosDocentes.setText("Exibir Funcionários Docentes");
        buttonFuncionariosDocentes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFuncionariosDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionariosDocentesActionPerformed(evt);
            }
        });

        buttonFuncionariosSubstitutos.setText("Exibir Funcionários Substitutos");
        buttonFuncionariosSubstitutos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFuncionariosSubstitutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionariosSubstitutosActionPerformed(evt);
            }
        });

        buttonFuncionariosEfetivos.setText("Exibir Funcionários Efetivos");
        buttonFuncionariosEfetivos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFuncionariosEfetivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFuncionariosEfetivosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelExibirFuncionariosLayout = new javax.swing.GroupLayout(panelExibirFuncionarios);
        panelExibirFuncionarios.setLayout(panelExibirFuncionariosLayout);
        panelExibirFuncionariosLayout.setHorizontalGroup(
            panelExibirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelExibirFuncionariosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelExibirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFuncionariosEfetivos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonTodosFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFuncionariosTecnicos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFuncionariosDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFuncionariosSubstitutos, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelExibirFuncionariosLayout.setVerticalGroup(
            panelExibirFuncionariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelExibirFuncionariosLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(buttonTodosFuncionarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFuncionariosTecnicos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFuncionariosDocentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFuncionariosSubstitutos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFuncionariosEfetivos)
                .addContainerGap())
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelComboDepartamento.setText("Exibir Informações do Departamento");

        btnInfoDepartamento.setText("Exibir");
        btnInfoDepartamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInfoDepartamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoDepartamentoActionPerformed(evt);
            }
        });

        comboDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Matemática", "Biologia", "Geografia", "Medicina" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(comboDepartamento, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnInfoDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(labelComboDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelComboDepartamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnInfoDepartamento)
                .addGap(73, 73, 73))
        );

        buttonRelatorioGeral.setText("Relatório Geral");
        buttonRelatorioGeral.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonRelatorioGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRelatorioGeralActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(panelRelatorioFaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnResumoDepartamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonRelatorioGeral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(panelExibirFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRelatorioFaixa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(20, 40, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRelatorioGeral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResumoDepartamentos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelRelatorioFaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRelatorioFaixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelExibirFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadastroActionPerformed
        // TODO add your handling code here:
        String nivelSelecionado = (String) comboNivel.getSelectedItem();
        if (nivelSelecionado.equals("Técnico")) {
            TelaCadastroTecnico IUCadTecnico = new TelaCadastroTecnico(this, true);
            IUCadTecnico.setLocationRelativeTo(this);
            IUCadTecnico.setVisible(true);
            int dep = IUCadTecnico.getDep();
            Funcionario func = IUCadTecnico.getFun();
            if(control.buscaFuncionarioCod(func.getCodigo()) == null){
              control.cadastrarFuncionario(func, dep);  
            } else JOptionPane.showMessageDialog(rootPane, "Funcionário já cadastrado com o código inserido");
        } else if (nivelSelecionado.equals("Efetivo")) {
            TelaCadastroEfetivo IUCadEfetivo = new TelaCadastroEfetivo(this, true);
            IUCadEfetivo.setLocationRelativeTo(this);
            IUCadEfetivo.setVisible(true);
            int dep = IUCadEfetivo.getDep();
            Funcionario func = IUCadEfetivo.getFun();
            if(control.buscaFuncionarioCod(func.getCodigo()) == null){
              control.cadastrarFuncionario(func, dep);  
            } else JOptionPane.showMessageDialog(rootPane, "Funcionário já cadastrado com o código inserido");
        } else {
            TelaCadastroSubstituto IUCadSubstituto = new TelaCadastroSubstituto(this, true);
            IUCadSubstituto.setLocationRelativeTo(this);
            IUCadSubstituto.setVisible(true);
            int dep = IUCadSubstituto.getDep();
            Funcionario func = IUCadSubstituto.getFun();
            if(control.buscaFuncionarioCod(func.getCodigo()) == null){
              control.cadastrarFuncionario(func, dep);  
            } else JOptionPane.showMessageDialog(rootPane, "Funcionário já cadastrado com o código inserido");
        }

    }//GEN-LAST:event_buttonCadastroActionPerformed

    private void buttonRelatorioGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRelatorioGeralActionPerformed
        // TODO add your handling code here:
        String s = control.relatorioGeral();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonRelatorioGeralActionPerformed

    private void comboNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboNivelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboNivelActionPerformed

    private void comboCodNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboCodNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboCodNomeActionPerformed

    private void textCodNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCodNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCodNomeActionPerformed

    private void textCodNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textCodNomeMouseClicked
        // TODO add your handling code here:
        textCodNome.setText("");
    }//GEN-LAST:event_textCodNomeMouseClicked

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        String codNome = (String) comboCodNome.getSelectedItem();
        String s = "";
        String textCodNome = this.textCodNome.getText();
        if (codNome.equals("Código")) {
            s = control.buscaFuncionarioCod(textCodNome);
        } else if (codNome.equals("Nome")) {
            s = control.buscaFuncionarioNome(textCodNome);
        }
        if (s == null) {
            s = "Funcionário não encontrado!";
        }
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnResumoDepFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumoDepFaixaActionPerformed
        // TODO add your handling code here:
        int min = (int) spinnerMin.getValue();
        int max = (int) spinnerMax.getValue();
        String s = control.resumoDepartamentosFaixa(min, max);
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_btnResumoDepFaixaActionPerformed

    private void btnResumoFuncFaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumoFuncFaixaActionPerformed
        // TODO add your handling code here:
        int min = (int) spinnerMinFunc.getValue();
        int max = (int) spinnerMaxFunc.getValue();
        String s = control.exibirFuncionariosFaixa((double) min, (double) max);
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_btnResumoFuncFaixaActionPerformed

    private void buttonTodosFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTodosFuncionariosActionPerformed
        // TODO add your handling code here:
        String s = control.exibirTodosFuncionarios();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonTodosFuncionariosActionPerformed

    private void btnResumoDepartamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResumoDepartamentosActionPerformed
        // TODO add your handling code here:
        String s = control.resumoDepartamentos();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_btnResumoDepartamentosActionPerformed

    private void buttonFuncionariosTecnicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionariosTecnicosActionPerformed
        // TODO add your handling code here:
        String s = control.exibirFuncionariosTecnicos();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonFuncionariosTecnicosActionPerformed

    private void buttonFuncionariosDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionariosDocentesActionPerformed
        // TODO add your handling code here:
        String s = control.exibirFuncionariosDocentes();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonFuncionariosDocentesActionPerformed

    private void buttonFuncionariosSubstitutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionariosSubstitutosActionPerformed
        // TODO add your handling code here:
        String s = control.exibirFuncionariosSubstitutos();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonFuncionariosSubstitutosActionPerformed

    private void buttonFuncionariosEfetivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFuncionariosEfetivosActionPerformed
        // TODO add your handling code here:
        String s = control.exibirFuncionariosEfetivos();
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_buttonFuncionariosEfetivosActionPerformed

    private void btnInfoDepartamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoDepartamentoActionPerformed
        // TODO add your handling code here:
        int op = comboDepartamento.getSelectedIndex();
        String s = control.exibirInfoDepartamento(op);
        TelaRelatorio relatorio = new TelaRelatorio(this, true, s);
        relatorio.setLocationRelativeTo(this);
        relatorio.setVisible(true);
    }//GEN-LAST:event_btnInfoDepartamentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnBuscar;
    private javax.swing.JButton btnInfoDepartamento;
    private javax.swing.JToggleButton btnResumoDepFaixa;
    private javax.swing.JToggleButton btnResumoDepartamentos;
    private javax.swing.JToggleButton btnResumoFuncFaixa;
    private javax.swing.JButton buttonCadastro;
    private javax.swing.JButton buttonFuncionariosDocentes;
    private javax.swing.JButton buttonFuncionariosEfetivos;
    private javax.swing.JButton buttonFuncionariosSubstitutos;
    private javax.swing.JButton buttonFuncionariosTecnicos;
    private javax.swing.JButton buttonRelatorioGeral;
    private javax.swing.JButton buttonTodosFuncionarios;
    private javax.swing.JComboBox<String> comboCodNome;
    private javax.swing.JComboBox<String> comboDepartamento;
    private javax.swing.JComboBox<String> comboNivel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelA;
    private javax.swing.JLabel labelA1;
    private javax.swing.JLabel labelCadastro;
    private javax.swing.JLabel labelComboCodNome;
    private javax.swing.JLabel labelComboDepartamento;
    private javax.swing.JLabel labelComboNivel;
    private javax.swing.JLabel labelDe;
    private javax.swing.JLabel labelDe1;
    private javax.swing.JLabel labelDepartamtoFaixa;
    private javax.swing.JLabel labelFuncionariaFaixa;
    private javax.swing.JPanel panelBuscar;
    private javax.swing.JPanel panelCadastro;
    private javax.swing.JPanel panelExibirFuncionarios;
    private javax.swing.JPanel panelRelatorioFaixa;
    private javax.swing.JPanel panelRelatorioFaixa1;
    private javax.swing.JSpinner spinnerMax;
    private javax.swing.JSpinner spinnerMaxFunc;
    private javax.swing.JSpinner spinnerMin;
    private javax.swing.JSpinner spinnerMinFunc;
    private javax.swing.JTextField textCodNome;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
